package model;
// Generated 12 nov. 2016 16:07:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Creneau generated by hbm2java
 */
public class Creneau  implements java.io.Serializable {


     private String creneauId;
     private String heureDebut;
     private String heureFin;
     private Set horaires = new HashSet(0);

    public Creneau() {
    }

	
    public Creneau(String creneauId, String heureDebut, String heureFin) {
        this.creneauId = creneauId;
        this.heureDebut = heureDebut;
        this.heureFin = heureFin;
    }
    public Creneau(String creneauId, String heureDebut, String heureFin, Set horaires) {
       this.creneauId = creneauId;
       this.heureDebut = heureDebut;
       this.heureFin = heureFin;
       this.horaires = horaires;
    }
   
    public String getCreneauId() {
        return this.creneauId;
    }
    
    public void setCreneauId(String creneauId) {
        this.creneauId = creneauId;
    }
    public String getHeureDebut() {
        return this.heureDebut;
    }
    
    public void setHeureDebut(String heureDebut) {
        this.heureDebut = heureDebut;
    }
    public String getHeureFin() {
        return this.heureFin;
    }
    
    public void setHeureFin(String heureFin) {
        this.heureFin = heureFin;
    }
    public Set getHoraires() {
        return this.horaires;
    }
    
    public void setHoraires(Set horaires) {
        this.horaires = horaires;
    }




}


