package model;
// Generated 12 nov. 2016 16:07:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HoraireId generated by hbm2java
 */
public class HoraireId  implements java.io.Serializable {


     private Date hdate;
     private String creneauId;
     private String salleId;

    public HoraireId() {
    }

    public HoraireId(Date hdate, String creneauId, String salleId) {
       this.hdate = hdate;
       this.creneauId = creneauId;
       this.salleId = salleId;
    }
   
    public Date getHdate() {
        return this.hdate;
    }
    
    public void setHdate(Date hdate) {
        this.hdate = hdate;
    }
    public String getCreneauId() {
        return this.creneauId;
    }
    
    public void setCreneauId(String creneauId) {
        this.creneauId = creneauId;
    }
    public String getSalleId() {
        return this.salleId;
    }
    
    public void setSalleId(String salleId) {
        this.salleId = salleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HoraireId) ) return false;
		 HoraireId castOther = ( HoraireId ) other; 
         
		 return ( (this.getHdate()==castOther.getHdate()) || ( this.getHdate()!=null && castOther.getHdate()!=null && this.getHdate().equals(castOther.getHdate()) ) )
 && ( (this.getCreneauId()==castOther.getCreneauId()) || ( this.getCreneauId()!=null && castOther.getCreneauId()!=null && this.getCreneauId().equals(castOther.getCreneauId()) ) )
 && ( (this.getSalleId()==castOther.getSalleId()) || ( this.getSalleId()!=null && castOther.getSalleId()!=null && this.getSalleId().equals(castOther.getSalleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHdate() == null ? 0 : this.getHdate().hashCode() );
         result = 37 * result + ( getCreneauId() == null ? 0 : this.getCreneauId().hashCode() );
         result = 37 * result + ( getSalleId() == null ? 0 : this.getSalleId().hashCode() );
         return result;
   }   


}


