package model;
// Generated 12 nov. 2016 16:07:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Niveau generated by hbm2java
 */
public class Niveau  implements java.io.Serializable {


     private String niveauId;
     private Byte ageMin;
     private Byte ageMax;
     private Set activites = new HashSet(0);

    public Niveau() {
    }

	
    public Niveau(String niveauId) {
        this.niveauId = niveauId;
    }
    public Niveau(String niveauId, Byte ageMin, Byte ageMax, Set activites) {
       this.niveauId = niveauId;
       this.ageMin = ageMin;
       this.ageMax = ageMax;
       this.activites = activites;
    }
   
    public String getNiveauId() {
        return this.niveauId;
    }
    
    public void setNiveauId(String niveauId) {
        this.niveauId = niveauId;
    }
    public Byte getAgeMin() {
        return this.ageMin;
    }
    
    public void setAgeMin(Byte ageMin) {
        this.ageMin = ageMin;
    }
    public Byte getAgeMax() {
        return this.ageMax;
    }
    
    public void setAgeMax(Byte ageMax) {
        this.ageMax = ageMax;
    }
    public Set getActivites() {
        return this.activites;
    }
    
    public void setActivites(Set activites) {
        this.activites = activites;
    }




}


