package model;
// Generated 12 nov. 2016 16:07:01 by Hibernate Tools 4.3.1



/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private int partcId;
     private Activite activite;
     private String nom;
     private String prenom;
     private String adresse;
     private String email;
     private String tel;

    public Participant() {
    }

	
    public Participant(int partcId, String nom, String prenom, String adresse, String email, String tel) {
        this.partcId = partcId;
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.email = email;
        this.tel = tel;
    }
    public Participant(int partcId, Activite activite, String nom, String prenom, String adresse, String email, String tel) {
       this.partcId = partcId;
       this.activite = activite;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.email = email;
       this.tel = tel;
    }
   
    public int getPartcId() {
        return this.partcId;
    }
    
    public void setPartcId(int partcId) {
        this.partcId = partcId;
    }
    public Activite getActivite() {
        return this.activite;
    }
    
    public void setActivite(Activite activite) {
        this.activite = activite;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


