package model;
// Generated 12 nov. 2016 16:07:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salle generated by hbm2java
 */
public class Salle  implements java.io.Serializable {


     private String salleId;
     private Byte capacite;
     private Set horaires = new HashSet(0);

    public Salle() {
    }

	
    public Salle(String salleId) {
        this.salleId = salleId;
    }
    public Salle(String salleId, Byte capacite, Set horaires) {
       this.salleId = salleId;
       this.capacite = capacite;
       this.horaires = horaires;
    }
   
    public String getSalleId() {
        return this.salleId;
    }
    
    public void setSalleId(String salleId) {
        this.salleId = salleId;
    }
    public Byte getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Byte capacite) {
        this.capacite = capacite;
    }
    public Set getHoraires() {
        return this.horaires;
    }
    
    public void setHoraires(Set horaires) {
        this.horaires = horaires;
    }




}


